//
//  SessionLocationStore.swift
//  WatchDog_iOS
//
//  Created by Sebastian Forenza 2026.
//
//  CoreLocation glue + per-session location persistence.
//
//  Lifecycle:
//    1. App or DevicePage opens → `requestAuthorizationIfNeeded()` prompts
//       the user once for "When in use" location permission. If they
//       decline, the map tab and detail-screen map degrade to "location
//       unavailable" empty states; nothing else breaks.
//    2. User holds the lock button → DevicePageView calls
//       `captureForUpcomingArm()`. We snapshot the most recent fresh
//       CLLocation into a `pending` slot tagged with `Date()`.
//    3. The arm settings packet reaches the firmware → firmware logs
//       SESSION_START → iOS drains the log → MotionLogManager.addMotionEvent
//       receives the SESSION_START.
//    4. addMotionEvent calls `associateIfPending(eventID:eventTimestamp:)`.
//       If the pending capture is recent enough (within `pendingWindow`),
//       we bind it to the SESSION_START's event id, clear pending, and
//       persist.
//    5. MotionReportView's Map tab and SessionDetailView read locations
//       by event id via `location(for:)`.
//
//  Why bind at SESSION_START time, not at arm time: the SESSION_START
//  event's UUID is generated by iOS when the BLE drain decodes it. We
//  don't know that UUID at arm time. The pendingWindow tolerates the
//  drain latency (typically <1s, but can stretch to ~5s during loyalty
//  reconnects); the timestamp match keeps an old pending entry from
//  attaching itself to an unrelated future SESSION_START.
//

import Foundation
import CoreLocation
import Observation

/// Plain-data location snapshot. Codable so the dictionary persists to
/// UserDefaults. Keeps just what the map needs — lat/lng, the moment we
/// captured it, and an optional user-supplied place name (reserved for
/// the "name this place" feature mentioned in the original session-design
/// thread).
struct SessionLocation: Codable, Hashable {
    let lat: Double
    let lng: Double
    let capturedAt: Date
    var placeName: String? = nil

    var coordinate: CLLocationCoordinate2D {
        CLLocationCoordinate2D(latitude: lat, longitude: lng)
    }
}

@Observable
class SessionLocationStore: NSObject, CLLocationManagerDelegate {
    static let shared = SessionLocationStore()

    /// Public read-only map: SESSION_START event id → captured location.
    /// Mutations all go through `associateIfPending` so persistence
    /// stays in sync.
    private(set) var locations: [UUID: SessionLocation] = [:]

    /// True once the user has been prompted at least once. We don't
    /// re-prompt — iOS handles re-asking via Settings → Privacy.
    private(set) var authorizationStatus: CLAuthorizationStatus = .notDetermined

    private let manager = CLLocationManager()
    private let storageKey = "watchdog_session_locations_v1"

    /// How long after capture we still consider the pending location
    /// fresh enough to associate with an arriving SESSION_START.
    /// Was 30 s — too tight. `associateIfPending` is called from
    /// MotionReportView.onAppear, not from the BLE-drain path, so the
    /// pending entry has to survive however long the user takes to open
    /// Motion Report after arming. 5 minutes is long enough for "lock
    /// the device, walk to the car, look at the app" while still short
    /// enough that an old pending entry doesn't attach to an unrelated
    /// future arm.
    private let pendingWindow: TimeInterval = 5 * 60

    /// Treat `manager.location` as authoritative only if its timestamp
    /// is within this window. CLLocationManager will happily hand back
    /// a one-hour-old cached fix when updates aren't running, which is
    /// worse than no location at all — it pins the SESSION_START to
    /// wherever the phone last had a fix, not where the user actually
    /// armed the device.
    private let maxLocationAgeSeconds: TimeInterval = 5 * 60

    private var pending: (location: SessionLocation, capturedAt: Date)?

    /// Set by `captureForUpcomingArm` when no fresh `manager.location`
    /// was available. `didUpdateLocations` watches this and, when a
    /// fresh fix arrives within `pendingWindow`, promotes the awaiting
    /// arm into a real `pending` entry. Without this, the previous
    /// implementation's `manager.requestLocation()` fallback was wasted —
    /// the one-shot result landed in an empty delegate and was discarded.
    private var pendingAwaitingFix: Date?

    override init() {
        super.init()
        manager.delegate = self
        manager.desiredAccuracy = kCLLocationAccuracyHundredMeters
        manager.distanceFilter  = 50
        authorizationStatus = manager.authorizationStatus
        loadFromDisk()

        // If the user previously granted permission, start updates now —
        // silently, no prompt. We want `manager.location` to be a fresh
        // fix by the time the user arms, NOT nil-because-no-updates or
        // a stale cached value from a previous app run. Touching the
        // singleton at app launch (see ContentView.onAppear) drives this
        // initialiser early enough to matter.
        if authorizationStatus == .authorizedWhenInUse
            || authorizationStatus == .authorizedAlways {
            manager.startUpdatingLocation()
        }
    }

    // MARK: - Authorization

    /// Call once early in the app lifecycle (we hook it from DevicePageView's
    /// onAppear). Idempotent — iOS only prompts the first time.
    func requestAuthorizationIfNeeded() {
        switch manager.authorizationStatus {
        case .notDetermined:
            manager.requestWhenInUseAuthorization()
        case .authorizedWhenInUse, .authorizedAlways:
            // Already authorized — start a low-frequency update so a
            // fresh `manager.location` is sitting in the cache the next
            // time the user arms. We stop updates once we have at least
            // one fix to avoid running the location daemon forever.
            manager.startUpdatingLocation()
        default:
            break
        }
    }

    // MARK: - Capture + associate

    /// Snapshot the latest known CLLocation into `pending`. Called by
    /// DevicePageView right before the arm settings packet goes out.
    /// If we don't have a recent fix (e.g. user just granted permission
    /// and hasn't moved), we kick a one-shot request — the SESSION_START
    /// drain typically takes long enough for the fix to come back before
    /// `associateIfPending` is called.
    func captureForUpcomingArm() {
        guard authorizationStatus == .authorizedWhenInUse
            || authorizationStatus == .authorizedAlways else {
            return
        }
        let now = Date()

        // Treat manager.location as authoritative only when it's both
        // valid (positive accuracy = not a "no fix" sentinel) AND fresh.
        // CLLocationManager hands back hour-old cached fixes when updates
        // aren't running — using those pins the arm to wherever the phone
        // last had a fix.
        if let loc = manager.location,
           loc.horizontalAccuracy > 0,
           now.timeIntervalSince(loc.timestamp) < maxLocationAgeSeconds {
            pending = (
                SessionLocation(lat: loc.coordinate.latitude,
                                lng: loc.coordinate.longitude,
                                capturedAt: now),
                now
            )
            pendingAwaitingFix = nil
        } else {
            // No fresh fix. Remember when the arm happened and lean on
            // the one-shot `requestLocation()` below — `didUpdateLocations`
            // will promote this into a real `pending` entry as soon as a
            // fix lands. Also kick continuous updates in case they weren't
            // running, so we have *some* stream to populate the cache for
            // future arms.
            pendingAwaitingFix = now
            manager.startUpdatingLocation()
        }
        manager.requestLocation()
    }

    /// Called from MotionLogManager.addMotionEvent for SESSION_START
    /// markers. Binds the most recent pending capture to this event id
    /// provided the pending capture was made within `pendingWindow`
    /// wall-clock seconds ago.
    ///
    /// Freshness is measured against `Date()`, NOT the event's reported
    /// timestamp. The firmware's anchor can be stale, mis-set, or zero
    /// (especially on the first SESSION_START of a boot, before iOS
    /// re-anchors the clock), and a comparison against `event.timestamp`
    /// would discard perfectly valid pending entries because of that
    /// drift. The pending entry is local-iOS time and we know when we
    /// stamped it.
    func associateIfPending(eventID: UUID, eventTimestamp: Date?) {
        _ = eventTimestamp  // intentionally unused; see comment above
        guard let pending else { return }
        if Date().timeIntervalSince(pending.capturedAt) > pendingWindow {
            self.pending = nil
            return
        }
        locations[eventID] = pending.location
        self.pending = nil
        saveToDisk()
    }

    func location(for sessionID: UUID) -> SessionLocation? {
        locations[sessionID]
    }

    /// Wipe locations belonging to the given session ids — keeps the
    /// disk store from accumulating orphan entries when the user
    /// clears sessions via the Motion Report menu.
    func forget(sessionIDs: Set<UUID>) {
        guard !sessionIDs.isEmpty else { return }
        let before = locations.count
        locations = locations.filter { !sessionIDs.contains($0.key) }
        if locations.count != before { saveToDisk() }
    }

    func forgetAll() {
        guard !locations.isEmpty else { return }
        locations = [:]
        saveToDisk()
    }

    // MARK: - Persistence

    private func saveToDisk() {
        // JSON dictionaries can only have String keys, so we serialise
        // the UUID → SessionLocation map by stringifying the UUIDs first
        // and rehydrating on load.
        let stringKeyed: [String: SessionLocation] = Dictionary(
            uniqueKeysWithValues: locations.map { ($0.key.uuidString, $0.value) }
        )
        do {
            let payload = try JSONEncoder().encode(stringKeyed)
            UserDefaults.standard.set(payload, forKey: storageKey)
        } catch {
            Log.err(.persist, "Save session locations · \(error)")
        }
    }

    private func loadFromDisk() {
        guard let data = UserDefaults.standard.data(forKey: storageKey) else { return }
        do {
            let stringKeyed = try JSONDecoder().decode([String: SessionLocation].self,
                                                       from: data)
            locations = Dictionary(uniqueKeysWithValues: stringKeyed.compactMap {
                guard let id = UUID(uuidString: $0.key) else { return nil }
                return (id, $0.value)
            })
        } catch {
            Log.err(.persist, "Load session locations · \(error)")
            locations = [:]
        }
    }

    // MARK: - CLLocationManagerDelegate

    func locationManager(_ manager: CLLocationManager,
                         didChangeAuthorization status: CLAuthorizationStatus) {
        authorizationStatus = status
        if status == .authorizedWhenInUse || status == .authorizedAlways {
            manager.startUpdatingLocation()
        }
    }

    func locationManagerDidChangeAuthorization(_ manager: CLLocationManager) {
        authorizationStatus = manager.authorizationStatus
        if manager.authorizationStatus == .authorizedWhenInUse
            || manager.authorizationStatus == .authorizedAlways {
            manager.startUpdatingLocation()
        }
    }

    func locationManager(_ manager: CLLocationManager,
                         didUpdateLocations locations: [CLLocation]) {
        // Intentionally do NOT stopUpdatingLocation here. The previous
        // implementation stopped after the first fix to save battery,
        // but that left manager.location frozen at the first-fix value
        // for the rest of the session — when the user moved to a new
        // place and locked there, captureForUpcomingArm() snapshotted
        // the stale fix or nil. Keeping updates running at
        // kCLLocationAccuracyHundredMeters + 50m distance filter is
        // low-cost (the system batches significant-motion deltas) and
        // makes the lock-time fix actually current.

        // Promote any awaiting-fix arm into a real pending entry. This
        // is the canonical fix for "sometimes the lock-time location
        // doesn't get tracked": captureForUpcomingArm fired before any
        // fix was available (app just launched, just granted permission,
        // or moved from background where updates were paused) and parked
        // an awaitingFix marker; the one-shot requestLocation() it kicked
        // is what we're seeing return here. Stamp the SessionLocation's
        // capturedAt with the arm time, not the fix arrival time, so the
        // 5-minute pendingWindow check downstream uses the right anchor.
        guard let fresh = locations.last, fresh.horizontalAccuracy > 0 else {
            return
        }
        if let awaiting = pendingAwaitingFix {
            if Date().timeIntervalSince(awaiting) <= pendingWindow {
                pending = (
                    SessionLocation(lat: fresh.coordinate.latitude,
                                    lng: fresh.coordinate.longitude,
                                    capturedAt: awaiting),
                    awaiting
                )
            }
            // Either we just promoted it or it expired before the fix
            // arrived — either way the awaiting marker is consumed.
            pendingAwaitingFix = nil
        }
    }

    func locationManager(_ manager: CLLocationManager, didFailWithError error: Error) {
        Log.warn(.persist, "Location update failed · \(error.localizedDescription)")
    }
}
